#!/bin/bash
set -x

DATETIME='[0-9]\{4\}-[0-9]\{2\}-[0-9]\{2\} [0-9]\{2\}:[0-9]\{2\}:[0-9]\{2\}'

get_last_analyzed_build_number(){
    local new_value=$1

    git clone https://github.com/snapcore/spread-cron.git target
    cd target
    git checkout $TRAVIS_BRANCH > /dev/null 2>&1
    total_commits=$(git rev-list --count HEAD)
    n=0
    while [ $n -lt $total_commits ]; do
        git log HEAD~${n} --pretty=%B | head -1 > log_entry
        if grep -q "^$message" log_entry; then
            old_value=$(sed -e "s|$message (\(.*\))|\1|" log_entry)
            if [ "$new_value" != "$old_value" ]; then
                build_number="$old_value"
                break
            fi
        fi
        n=$((n+1))
    done
    if [ -z "$build_number" ]; then
        # we didn't find any previous execution, start from the first build
        build_number="1"
    fi
    echo "$build_number"
}
. ./options
last_build_number=$(echo "$TRAVIS_COMMIT_MESSAGE" | sed -e "s/$message (\(.*\))/\1/")
last_analyzed_build_number=$(get_last_analyzed_build_number $last_build_number)
current_build_number=$last_build_number
order=0
while [ $current_build_number -gt $last_analyzed_build_number ]; do
    # get build log
    build=$(curl -s https://api.travis-ci.org/repos/snapcore/snapd/builds?number=${current_build_number})
    branch=$(echo "$build" | jq -j '.[0].branch')
    build_id=$(echo "$build" | jq '.[0].id')
    result=$(echo "$build" | jq '.[0].result')
    job_id=$(curl -s "https://api.travis-ci.org/repos/snapcore/snapd/builds/${build_id}" | jq '.matrix[2].id')

    curl -s "https://s3.amazonaws.com/archive.travis-ci.org/jobs/${job_id}/log.txt" -o spread.log

    # remove initial lines and travis time marks only leaving spread output
    sed -i -n '/'"$DATETIME"' Found \/home\/travis\/gopath\/src\/github.com\/snapcore\/snapd\/spread.yaml./,$p' spread.log
    sed -i 's/^travis_.*$//' spread.log
    sed -i '/^\s*$/d' spread.log

    # mark first and last entries
    sed -i '0,/'"$DATETIME"'/s/\('"$DATETIME"'\) \(.*\)/\1 |events-start| \2/' spread.log
    sed -i ':a;$!{N;ba};s/\(.*\)\('"$DATETIME"'\)\(.*\)/\1\2 |events-end| \3/' spread.log

    # insert build number, branch and result in log entries
    sed -i '/^'"$DATETIME"'/s/^/<'"$current_build_number"'> <'"$branch"'> <'"$result"'> /' spread.log

    # move to filebeat path
    current_file="/tmp/spread-${current_build_number}.log"
    mv spread.log "$current_file"

    # wait for filebeat to finish with this file
    current_file_size=$(stat --printf="%s" "$current_file")
    while [ $(jq -j '.['"$order"'].offset' /var/lib/filebeat/registry) != "$current_file_size" ];do
        sleep 1
    done

    current_build_number=$((current_build_number-1))
    order=$(($order+1))
done
