#!/bin/sh

mkdir -p bin
( cd bin &&  wget https://niemeyer.s3.amazonaws.com/spread-amd64.tar.gz -O spread.tar.gz && tar xzvf spread.tar.gz )
git clone https://github.com/snapcore/snapd target

export SPREAD_NESTED_ARCH=amd64
cd target && ../bin/spread -v linode:ubuntu-16.04-64:tests/nested/
